@startuml dynamic seuquence

hide footbox
title ダイナミックシーケンス図(経費申請)

box "SPA-Vue.js(ブラウザ)"
actor 社員 as User
end box

box "フレームワークとドライバ"
boundary Express as index

database DBモデル as dbmodel
end box
box "インターフェイスアダプター"
control "コントローラ" as controller
control "リポジトリ" as repository
end box
box "ユースケース"
participant Submit
end box
box "エンティティ"
entity "Expense" as domains
end box

User->index : Expense (JSON)
activate index
index->controller : Expense(req.body)
activate controller
controller->Submit : IExpenseValue
activate Submit
Submit->domains : Create Expense
activate domains
domains->domains : Checking Validation
domains->Submit : ExpenseEntity
deactivate domains
Submit->repository : ExpenseEntity
activate repository
repository->dbmodel : IExpenseValue
activate dbmodel
dbmodel->repository : IExpenseValue
deactivate dbmodel
repository->Submit : ExpenseEntity
deactivate repository
Submit->controller : ExpenseEntity
deactivate Submit
controller->index : IExpenseValue
deactivate controller
index->User : Expense (JSON)
deactivate index

@enduml