@startuml

package 請求システム as expense_system {
  entity "請求" as expense {
    + id [PK]
    --
    # user_id [FK]
    user_name : 不要
    data
    type
    description
    amount
    created_at
    updated_at
  }
}

package ユーザ管理 as user_management {
  entity "ユーザマスタ" as user {
    + id [PK]
    --
    # boss_id [FK]
    first_name
    last_name
    email
    hash
    salt
    created_at
    updated_at
    deleted_at
  }

  entity "権限" as role {
    + id [PK]
    --
    # user_id [FK]
    name
    created_at
    updated_at
  }
}

  user ||--|{ role
  user ||--o{ expense

@enduml