@startuml usecases

left to right direction

actor User
actor Approver
actor Accounting

Approver --|> User
Accounting --|> User

rectangle Usecases {
  package Common {
    User -> (Login)
    Approver -> (Login)
    Accounting -> (Login)
  }

  package Expense {
    User -> (View Rejected)
    User -> (Submit)
    User -> (Update)
  }

  package Approval {
    Approver -> (View Unapproved)
    Approver -> (Approve)
    Approver -> (Reject)
  }

  package Payment {
    Accounting -> (View Approved)
    Accounting -> (Pay)
    Accounting -> (Reject)
  }
}

@enduml

